# Generated by Django 5.0.4 on 2025-04-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_news_options_alter_news_avtor_alter_news_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
