# Generated by Django 5.0.4 on 2025-04-12 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='default-img.jpg', null=True, upload_to='pictures/news_images'),
        ),
    ]
