# Generated by Django 5.0.4 on 2025-04-18 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_news_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, default='default-img.jpg', null=True, upload_to='news_images'),
        ),
    ]
